# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-SITQmWiV-T_TflSV1uX0kJF6vEBNu7s
"""

import streamlit as st
import numpy as np
import joblib
from PIL import Image
import cv2

from skimage.io import imread
from skimage.transform import resize
from skimage.color import rgb2hsv, hsv2rgb
from skimage.exposure import equalize_adapthist, rescale_intensity
from skimage.filters import gaussian

import matplotlib.pyplot as plt

# ================= PAGE CONFIG =================
st.set_page_config(
    page_title="Skin Disease Detection",
    layout="centered"
)

st.title("Skin Disease Detection")
st.caption("Machine Learning–based Skin Disease Classification")
st.divider()

# ================= LOAD MODEL =================
model = joblib.load("xgboost_model.pkl")
scaler = joblib.load("scaler.pkl")
label_encoder = joblib.load("label_encoder.pkl")

# ================= DISEASE DESCRIPTIONS =================
DISEASE_INFO = {
    "Acne and Rosacea Photos":
        "Inflammatory skin conditions involving redness, pimples, and clogged pores.",
    "Eczema Photos":
        "A chronic condition causing itchy, inflamed, and dry skin.",
    "Psoriasis pictures Lichen Planus and related diseases":
        "An autoimmune disease leading to rapid skin cell buildup.",
    "Melanoma Skin Cancer Nevi and Moles":
        "A serious form of skin cancer originating from melanocytes.",
    "Tinea Ringworm Candidiasis and other Fungal Infections":
        "Fungal infections affecting skin, nails, or scalp."
}
def preprocess_image(path_or_img):
    """
    Preprocess gambar dengan normalisasi lebih baik.
    Pipeline DISAMAKAN dengan training.
    """

    if isinstance(path_or_img, str):
        img = imread(path_or_img)
    else:
        img = np.array(path_or_img)

    img = resize(img, (256, 256), anti_aliasing=True)

    hsv = rgb2hsv(img)
    hsv[..., 2] = equalize_adapthist(hsv[..., 2], clip_limit=0.03)
    img = hsv2rgb(hsv)

    for i in range(3):
        p2, p98 = np.percentile(img[..., i], (2, 98))
        img[..., i] = rescale_intensity(
            img[..., i],
            in_range=(p2, p98)
        )

    img = np.clip(img, 0, 1)

    img = gaussian(img, sigma=0.5, channel_axis=-1)

    img = img.flatten()
    img = scaler.transform([img])

    return img

uploaded_file = st.file_uploader(
    "Upload a skin image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")

    st.image(
        image,
        caption="Uploaded Image",
        use_column_width=True
    )

    if st.button("Predict Disease"):
        X = preprocess_image(image)

        probs = model.predict_proba(X)[0]
        classes = label_encoder.classes_

        top_idx = np.argsort(probs)[::-1][:3]

        main_class = classes[top_idx[0]]
        main_conf = probs[top_idx[0]] * 100

        st.success(f"Prediction: **{main_class}** ({main_conf:.2f}%)")


        st.subheader("Disease Description")
        st.write(
            DISEASE_INFO.get(
                main_class,
                "No detailed description available for this condition."
            )
        )


        st.subheader("Prediction Confidence")

        fig, ax = plt.subplots()
        labels = [classes[i] for i in top_idx]
        values = [probs[i] * 100 for i in top_idx]

        ax.barh(labels, values)
        ax.set_xlabel("Confidence (%)")
        ax.invert_yaxis()

        for i, v in enumerate(values):
            ax.text(v + 0.5, i, f"{v:.2f}%", va="center")

        st.pyplot(fig)


        st.subheader("Top 3 Predictions")
        for i in top_idx:
            st.write(f"- {classes[i]}: {probs[i]*100:.2f}%")

        st.warning(
            "This application is for educational purposes only "
            "and must not be used as a medical diagnosis."
        )